### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by groveham** [MCServerTools/ServerTools-PERMISSION#12]
Getting a lot of console spam to do with:

info.servertools.permission.asm.STPClassTransformer

Not sure if it's causing any issues but there seems to be a lot of it, I've uploaded the latest log below:

https://www.dropbox.com/s/zz6x4x3f1utnavy/fml-server-latest.log?dl=0

**Comment by QORTEC** [comment]
I too also have its issue. I ran my server for a little over an hr and 23% of the lines contain the above string above.

Server Ran form 23:40:32 to 00:10:42
fml-server-latest.log size is 85997 lines long
20133 lines contain info.servertools.permission.asm.STPClassTransformer: 

[I got the 20133 number form gedit ctrl+f]
If another 12-13 MB log file would help I would be happy to upload it (compressed or uncompressed).
