### ISSUE TITLE
Command Block Editing

### ISSUE THREAD

**Issue by julliande** [MCServerTools/ServerTools-PERMISSION#13]
Hi there, I am running a 1.7.10 kcauldron server with ServerTools Core | Teleport | Permissions installed on it and when specifically SeverTools Permissions is installed I am unable to edit command blocks.

I am an op and command blocks have been enabled on the server however is tells me:
"Must be opped and in creative mode" and deletes the text that I type into the command block.

I haven't had any other issues with ServerTools and I have been using it on this server for about a month.
.
Any ideas why permissions would be stopping me from editing a command block?

**Comment by matthewprenger** [comment]
ServerTools-Permission doesn't touch command blocks. I'm guessing cauldron is blocking you, see if you can replicate the problem without it.

**Comment by julliande** [comment]
After some testing this is what I have to offer:

- Compatible with fresh installs of Forge and KCauldron respectively using ServerTools Core | Permissions | Teleport
- Compatible with my KCauldron Server running 85+ mods and 2 plugins
- By copying the original Admin and Moderator files from a fresh install (of your mod) into my online server I am now able to use command blocks properly.
- I see one permission in the original Moderator group that I know nothing about (couldn't find anything online either) called "cmd.forge" what is this?
- Is there some reason that removing these groups would cause issues?
- Can I give command block use permission to a specific group who are not considered admins/ops?

Prior to this testing: For my actual server I deleted both the original Admin and Moderator groups because I hadn't noticed them till after I had made my own groups by those names with tons of permissions for each. So as I said above: Is there a reason deleting those original groups would cause issues? Does cmd.forge have anything to do with it?

**Comment by julliande** [comment]
This is what I was about to send:
****************************************************************************************
Okay, so I just discovered this:

On my online server if I replace the Permissions module and then OP a player they are able to use command blocks. However if I also add them to another group, for example "Admin", the server will then prompt that they need to be an operator for some reason.

I also attempted to /removeplayer from the extra group they are in but it does not fix the issue. It will continuously tell the player that they "...need to be an OP in creative mode..." to edit command blocks.

This issue did not occur on the fresh install of KCauldron which was running only ServerTools Core | Permissions | Teleport. I also tried it with the two plugins I am using and it worked fine.

It seems like the addplayer command triggers something else to go funky in my online server. Do you have any idea what might be causing the problem? I have a ton of mods installed but none of them should be editing or deleting permissions.
*******************************************************************************

And then I solved the problem:
When I originally installed ServerTools I did not plan on using command blocks so I never noticed this. The first thing I did after installing the mod was create my own groups called "admin" and "moderator."

Later on I realized there were groups already called Moderator and Admin in the groups folder so I deleted the auto generated ones so that I would not lose all the work I had put into adding permissions to MY groups. This appears to be my mistake/a bug with the mod (Or intended feature?).

I fixed this by copying the Player.json, Moderator.json and Admin.json files that are originally created by the Permissions module and placing these new files into my online server (I also deleted the groups I created). I have not noticed any issues regarding command blocks or anything else so far. Adding and removing players from these original groups works and does not cause issues.

Maybe the issue occurs only when the original three groups are deleted? I thought they were just example files. Do they need to be left alone?

Sorry if any of this is confusing I am super tired. Let me know if you need me to reword or clarify something.

**Comment by julliande** [comment]
Last one for tonight. This one is short sweet and to the point. (You can read above if you want to follow my troubleshooting/testing)

It appears that the only way I can edit command blocks is if I am a member of the Admin group that is originally created by the Permissions module. When the Permissions module is active the game doesn't care if I am actually OP (using the op command.) It only cares that I am a member of the Admin permissions group.

So why is this happening and how do I give command block privileges to other groups without making them "Admin" group members?

**Comment by matthewprenger** [comment]
The `cmd.forge` permission is the permission needed to execute the `/forge` command. That's how ServerTools-Permission works.

The only time ServerTools-Permission is involved is when a command is executed. Instead of the normal OP checks for if a player can use it or not, Minecraft will delegate to ServerTools to decide who can run what commands. That's all ServerTools-Permission does, it doesn't mess with command blocks at all so I'm still not sure how ServerTools is causing the issue.

As for the default groups (Admin, Moderator, Player), those are generated whenever no existing groups are detected (usually only the first run of the server). At this point ServerTools will actually scan through all the registered commands and auto-add the permissions for them to the groups that make sense. It uses the `requiredPermissionLevel` that is built into all Minecraft commands to determine this.

**Comment by julliande** [comment]
How does ServerTools decide if a group is the right permissionlevel to use
certain commands or in this case a command block?

Do I just need to add a level 2-4 command to a group for that group to
register as the corresponding permission level?

I did not give my groups many vanilla commands.  It's possible they never
had access to anything over permission level 1. That would make them unable
to use command blocks if this is true.

**Comment by matthewprenger** [comment]
I don't think you understand me, the numerical permission levels are only used for the *default* group generation. They aren't used for actual permission checking.
