### ISSUE TITLE
MyTown2 Commands not processed

### ISSUE THREAD

**Issue by groveham** [MCServerTools/ServerTools-PERMISSION#15]
For some reason, my players can't use the /t or /town command. I've added both and can clearly see them in the 'Player' permissions file as cmd.t and cmd.town. This has worked for other commands outside the mod such as Opis and players are able to access it.
When trying to do /t or /town they get access denied. There are no errors in the log, no crash reports so I'm wondering why ServerTools Permissions it's pulling through the perms and allowing access, can you help?

Using the following: 
ServerTools-CORE-1.7.10-2.2.0.79.jar
ServerTools-PERMISSION-1.7.10-2.2.1.7.jar
ServerTools-TELEPORT-1.7.10-2.2.0.13.jar
MyTown2-1.7.10-0.1.1b.jar
Forge 10.13.4.1490

**Comment by matthewprenger** [comment]
I'm guessing MyTown is doing it's own permission checking. Not really much I can do from my side.

**Comment by groveham** [comment]
Confirmed, MyTown2 didn't know you had a permissions mod, they will add the support on their side.
